services:
  waha:
    image: devlikeapro/waha:latest
    container_name: wpp_bot_wahaaa
    restart: always
    ports:
      - '3000:3000'
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: wpp_bot_api
    ports:
      - '5000:5000'
    volumes:
      - .:/app
      - ./chroma_data:/app/chroma_data


